### ISSUE TITLE
Question: How to set drop down menu colors

### ISSUE THREAD

**Issue by AchimKern** [EnviralDesign/UberGui#25]
Hey Lucas ,

is there a way to configure the dropdown options:
- bg colors
- spacing 
- scrollbar colors and size?
- overall width and height

Also it's a bit weird that the dropdowns rollover color is controlled by accentinteractcolor  and not via hovercolor

cheers
Achim

**Comment by EnviralDesign** [comment]
Hi Achim,

bg colors and rollover colors are specified via the Interact parameters below:
![image](https://user-images.githubusercontent.com/10091486/116138381-5b305280-a69a-11eb-9c9c-46307abfb945.png)
This was added as separate color params because it influences not just the menu picker but also various elements in the color picker and field, which are all helper UI's with similar visual styling.

Spacing wasn't controlled (now it is) using the parameter called "All Parameter Margins".  

dropdown scrollbar color is not controllable since it is the container scrollbar (I've put in an rfe with derivative about this), but the scrollbar width can be controlled (and now is) by the general scrollbar width parameter.

overall width and height was not controllable, but I could see width being constraining if the menu items were long strings, so I made an option in the style page to set the menu width to the width of the parameter, or the full width of UberGui.
the height was hard coded to 4.5 times the height of a menu item's height, now that multiplier is available in the style page as well.  If you set something too large, it is constrained to fit within the dims of the ubergui parent container.

I'm going to close this but if there is some specific use cases you can provide through a tox with custom parameters where it's still tricky to use, or aesthetically unpleasing, etc attach that to a new issue and I'll take a look and we can see what would be the best way to make that happen.

Thanks!
