### ISSUE TITLE
First touch after mouse movement no recognised 

### ISSUE THREAD

**Issue by AchimKern** [EnviralDesign/UberGui#29]
On a touchscreen, the first touch after moving the mouse is not recognized

And touching and moving a slider and then selecting and moving a different slider will actually move the previous slider/par

**Comment by EnviralDesign** [comment]
I'm able to recreate the second thing here, where moving a dif slider always moves the previous one. This must be an artifact of the newest 2021 builds somehow, taking a look now.

Touchscreen input has bee troubling to get right in because the UI pick info is coming from a threaded instance and can't reliably be guaranteed to be up to date in same frame if ever.  Touchscreen usage lacks the awareness of mouse hovering which solves this problem by determining the parameter of interaction by hovered item which always happens a few frames before the actual interaction.

**Comment by EnviralDesign** [comment]
Okay the bugs mentioned have been fixed along with some other refactoring of storage to internal params - you can get this most up to date stuff on the 4.1.0 branch but I'll push it all to main after I get through some more items and test more thoroughly.
